services:
  ddf:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ddf-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ddf
    networks:
      - my-network
  gps:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - gps-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=gps
    networks:
      - my-network
  pim:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - pim-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=pim
    networks:
      - my-network

volumes:
  grafana-storage: {}
  ddf-storage: {}
  gps-storage: {}
  pim-storage: {}

networks:
  my-network:
    external: false